app/maintracker/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, SelectField, SubmitField, TextAreaField, PasswordField
from wtforms import ValidationError
from wtforms.validators import Required, length
from wtforms.validators import Required, Email, Length, EqualTo
from app.model import User, Items
from .. import db

class MaintananceForm(Form):
	item_name = StringField('Item Name', validators=[Required()])
	item_issue = StringField('Item Issue', validators=[Required()])
	item_type = StringField('Item Type', validators=[Required()])
	status = SelectField(
		'Status',
		choices=[('needs repair', 'Needs Repair'), ('needs maintanance', 'Needs Maintanance')]
	)
	submit = SubmitField('Raise')

class ApproveForm(Form):
	item_name = StringField('Item Name', validators=[Required()])
	item_issue = StringField('Item Issue', validators=[Required()])
	item_type = StringField('Item Type', validators=[Required()])
	comment = TextAreaField("Admin's Comment")
	submit = SubmitField('Approve')
	reject = SubmitField('Reject')

class AssignForm(Form):
	
	assignees = SelectField(id=User.id, choices=User.query.with_entities(User.id, User.full_name ).all(), coerce=int)
	submit = SubmitField('Assign')


class AddUserForm(Form):

	first_name = StringField('FirstName', validators=[Required(), Length(1, 20)])
	last_name = StringField('LastName', validators=[Required(), Length(1, 20)])
	email = StringField('Email', validators=[Required(), Length(1, 64), Email()])
	phone_number = StringField('PhoneNumber', validators=[Required(), Length(1, 64)])
	password = PasswordField('Password', validators=[Required(), EqualTo('conf_password', message='Passwords must match.')])
	conf_password = PasswordField('Confirm password', validators=[Required()])
	submit = SubmitField('Add User')

	
	def validate_email(self, field):
		
		if User.query.filter_by(email=field.data).first():
			raise ValidationError('Email already registered.')

app/__init__.py
from flask_sqlalchemy import SQLAlchemy
import os
from config import config
from flask import Flask
from flask_login import LoginManager
from flask_bootstrap import Bootstrap

basedir = os.path.abspath(os.path.dirname(__file__))
app = Flask(__name__)

db = SQLAlchemy(app)
login_manager = LoginManager()

bootstrap = Bootstrap()
# can be set to basic ,None or strong
# it keeps track of the browser the user is using
login_manager.session_protection = 'None'
# The login_view
# attribute sets the endpoint for the login page. Recall that because the login route is inside
# a blueprint, it needs to be prefixed with the blueprint name.
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    app.config['SECRET_KEY'] = 'hard to guess string'
    db = SQLAlchemy(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)

    from auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from maintracker import main as main_blueprint
    app.register_blueprint(main_blueprint)
    return app

app/maintracker/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/maintracker/views.py
from . import main
from flask import render_template
from .forms import AddUserForm, ApproveForm, MaintananceForm, AssignForm
from ..model import User, Items, Assigned
from .. import db
from flask import render_template, redirect, url_for, request, flash, session
from flask.ext.login import logout_user, current_user, login_required


@main.route('/')
@main.route('/home')
def home_page():
    return render_template('maintracker/home.html')




@main.route('/base', methods=['GET', 'POST'])
@login_required
def base():
    maintanances = (Items.query.filter_by(raised_by=current_user.email))
    approved = (Items.query.filter_by(status="Under Repair"))
    assigned = (Items.query.filter_by(assigned_to=current_user.full_name))
    return render_template('base.html', maintanances=maintanances, approved=approved, assigned=assigned)


@main.route('/maintanance', methods=['GET', 'POST'])
@login_required
def maintanance():
    main_form = MaintananceForm()
    if main_form.validate_on_submit():
        main = Items(item_name=main_form.item_name.data,
            item_issue=main_form.item_issue.data,
            item_type=main_form.item_type.data,
            status=main_form.status.data,
            assigned_to="Not Assigned",
            raised_by=current_user.email)
        db.session.add(main)
        db.session.commit()
        flash("Maintanance request submitted successfully.")
        return redirect(url_for('main.base'))
    return render_template('maintracker/maintanance.html', main_form=main_form)
    

@main.route('/admin_home', methods=['GET', 'POST'])
@login_required
def admin_home():
    maintanances = (Items.query.filter_by(status='Needs Repair').all())
    
    return render_template('admin/admin_home.html', maintanances=maintanances)



@main.route('/admin_mains', methods=['GET', 'POST'])
@login_required
def admin_mains():
    maintanances = Items.query.all()
    return render_template('admin/maintanance.html', maintanances=maintanances)


@main.route('/admin_users', methods=['GET', 'POST'])
@login_required
def admin_users():
    users = User.query.all()
    return render_template('admin/users.html', users=users)


@main.route('/approve/<int:id>', methods=['GET', 'POST'])
@login_required
def approve(id):
    item = Items.query.get_or_404(id)
    approve_form = ApproveForm()
    main_form = MaintananceForm()
    if approve_form.validate_on_submit():
        item.status = "Under Repair"
        item.comment = approve_form.comment.data
        db.session.add(item)
        db.session.commit()
        flash("Maintanance request submitted successfully")
        return redirect(url_for('main.admin_mains'))
    approve_form.item_name.data = item.item_name
    approve_form.item_issue.data = item.item_issue
    approve_form.item_type.data = item.item_type
    return render_template('admin/approvereject.html', approve_form=approve_form)


@main.route('/admin_add_user', methods=['GET', 'POST'])
@login_required
def admin_add_user():
    user_form = AddUserForm()
    if user_form.validate_on_submit():
        user = User(first_name=user_form.first_name.data,
            last_name=user_form.last_name.data,
            email=user_form.email.data,
            phone_number=user_form.phone_number.data,
            password=user_form.password.data,
            role="admin")
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.admin_mains'))
    return render_template('admin/add_user.html', user_form=user_form)


@main.route('/assign/<int:id>', methods=['GET', 'POST'])
@login_required
def assign(id):
    item = Items.query.get_or_404(id)
    assign_form = AssignForm(request.form)
    if assign_form.validate_on_submit():
        item.assign_to = assign_form.assignees.data
        db.session.commit()
        return redirect(url_for('main.admin_home'))

    return render_template('admin/assign.html', assign_form=assign_form, item=item, id=id)

app/templates/base.html
<!-- base.html template -->
{% import "bootstrap/wtf.html" as wtf %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/demo.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/header-second-bar.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css') }}">
    <link href='http://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

<style>
body {
  font: 13px/20px "Open Sans", Tahoma, Verdana, sans-serif;
  color: #000000;
  background-image: url("static/bg.jpg")
}
</style>

</head>

 
 
<header class="header-two-bars">

    <div class="header-first-bar">

        <div class="header-limiter">

            <h1 style="color:#000000;"><a href="#"><span>Maintanance Tracker</span></a></h1>
            {% if current_user.is_authenticated %}
             <a href="" class="logout-button">{{ current_user.email }}</a>
             {% endif %}
            <a href="{{ url_for('auth.sign_out') }}" class="logout-button">Logout</a>
        </div>

    </div>

    <div class="header-second-bar">
        <div class="header-limiter">
            <h2><a href="#"></a></h2>
         {% block navbar %}
            <nav>
                <a href="{{ url_for('main.maintanance') }}" class = "btn btn-info">Report Maintanance/Repair</a>
                
            </nav>
         {% endblock %}

        </div>

    </div>

</header>


<!-- The content of your page would go here. -->
{% block page_content %} 
<div class="container">
  <div class="row">
<div class="panel panel-default">
        <div class="panel-heading">
          <h4>
            Requested maintanance/Repairs
          </h4>
      </div>
<table  class="table table-striped table-bordered table-condensed table-hover" width="647">
  
   
   <thead>
      <tr>
         <th>Item Name</th>
         <th>Item Issue</th>
         <th>Item Type</th>
         <th>Status</th>
      </tr>
   </thead>
   {% for maintanances in maintanances%}
   <tbody>
    <tr>
       <td>{{ maintanances.item_name }}</td>
       <td>{{ maintanances.item_issue }}</td>
       <td>{{ maintanances.item_type }}</td>
       <td>{{ maintanances.status }}</td>
    </tr>
  </tbody>
   {% endfor %}
</table>
</div>
</div>
</div>


<div class="container">
  <div class="row">
<div class="panel panel-default">
        <div class="panel-heading">
          <h4>
            Approved/Rejected Maintanance/Repairs
          </h4>
      </div>
<table  class="table table-striped table-bordered table-condensed table-hover" width="647">
  
   
   <thead>
      <tr>
         <th>Item Name</th>
         <th>Item Issue</th>
         <th>Comment</th>
         
      </tr>
   </thead>
   {% for approved in approved%}
   <tbody>
      <tr>
         <td>{{ approved.item_name }}</td>
         <td>{{ approved.item_issue }}</td>
         <td>{{ approved.comment }}</td>
      </tr>
    </tbody>
   {% endfor %}
</table>
</div>
</div>
</div>



<div class="container">
  <div class="row">
<div class="panel panel-default">
        <div class="panel-heading">
          <h4>
            Assigned Items
          </h4>
      </div>
<table  class="table table-striped table-bordered table-condensed table-hover" width="647">
  
   
   <thead>
      <tr>
         <th>Item Name</th>
         <th>Item Issue</th>
         <th>Raised by</th>
         
      </tr>
   </thead>
   {% for approved in approved%}
   <tbody>
      <tr>
         <td>{{ assigned.item_name }}</td>
         <td>{{ assigned.item_issue }}</td>
         <td>{{ assigned.raised_by }}</td>
      </tr>
    </tbody>
   {% endfor %}
</table>
</div>
</div>
</div>
{% endblock %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://cdn.tutorialzine.com/misc/enhance/v3.js" async></script>
</html>

app/templates/maintracker/home.html
<!DOCTYPE html>
<html >
  <head>
	<meta charset="UTF-8">
	<title>Maintanance Tracker</title>
	
   <link rel="stylesheet" href="static/css/style1.css">
   <link rel="stylesheet" href="static/bootstrap/css/bootstrap.css">
   <style>
body {
  font: 13px/20px "Open Sans", Tahoma, Verdana, sans-serif;
  color: #a7a599;
  background-image: url("static/bg.jpg")
}
</style>
  </head>

  <body>

	<div class="wrapper">
	<div class="container">
		<h1>Maintanance Tracker</h1>
		
		<form class="form">
			<div class = "row">
			<a href="sign_in" class="btn btn-default btn-lg btn-block" role="button" aria-pressed="true">Sign In</a>
			</div>
			<br/>
			<div>
			<a href="sign_up" class="btn btn-default btn-lg btn-block" role="button" aria-pressed="true">Sign Up</a>
			</div>
	   </form>
	</div>
	
	<ul class="bg-bubbles">
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
	</ul>
</div>
	<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

		<script src="static/js/index.js"></script>

	
	
	
  </body>
</html>

app/templates/maintracker/maintanance.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

 
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,600' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="static/css/normalize.css">
  <link rel="stylesheet" href="static/css/style.css">
  <link rel="stylesheet" href="static/bootstrap/css/bootstrap.css">



<nav>
<a href="#" class = "btn btn-primary"> Maintanance/Repair</a>
</nav>


{% block page_content %}
	<div class="container">
    <div class="row">
        <div class="col-md-8">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Maintanance/Repair Form</h3>
          </div>
          <div class="panel-body">
    	
        <form role="form" method="POST" action="{{ url_for('main.maintanance') }}" class="form col-md-5">
            {{ main_form.hidden_tag() }}
            <div class="row">
                 <div class="column">
                    
                    
                        {{ wtf.form_field(main_form.item_name) }}
                        
                    </div>
                </div>
                <div class="row">
                 <div class="column">
                        {{ wtf.form_field(main_form.item_issue) }}
                        
                    </div>
                </div>
                <div class="row">
                 <div class="column">
                        {{ wtf.form_field(main_form.item_type) }}
                       
                    </div>
                </div>
                <div class="row">
                 <div class="column">
                        {{ wtf.form_field(main_form.status) }}
                        
                    </div>
                </div>
                {{ wtf.form_field(main_form.submit) }}
               
            </div>
        </form>
   
        
    </div>
</div>
</div>
</div>

{% endblock %}